export const data =[
    {   category:"Frontend",
        question:"What is HTML used for?",
        option1:"Hypertext Markup Language",
        option2:"High-level Text Management Language",
        option3:"Hyper Transfer Markup Language",
        ans :1,
    },
    {
        category:"Frontend",
        question:"Which CSS property is used to change the text color of an element?",
        option1:" color",
        option2:"font-color",
        option3:"text-color",
        ans :1,
    },
    {   category:"Frontend",
        question:"What does the acronym CSS stand for?",
        option1:"Counter Style Sheets",
        option2:"Computer Style Sheets",
        option3:"Cascading Style Sheets",
        ans :3,
    },


    {   category:"Frontend",
        question:"What is the purpose of JavaScript in web development?",
        option1:"Database management",
        option2:"Styling the webpage",
        option3:"Adding interactivity to the webpage",
        ans :3,
    },
    {
        category:"Frontend",
        question:"How do you declare a variable in JavaScript?",
        option1:"let myVar;",
        option2:"variable myVar;",
        option3:"var myVar;",
        ans :1,
    },
    {   category:"Frontend",
        question:"What does the term \"responsive design\" refer to in web development?",
        option1:"Designing web pages that respond to user interactions",
        option2:"Designing web pages that adapt to different screen sizes",
        option3:"Designing web pages with vibrant colors",
        ans :2,
    },

// questions de  backend :

    {   category:"backend",
        question:"What does the acronym SQL stand for in the context of databases?",
        option1:" Structured Query Language",
        option2:"Simple Query Language",
        option3:"System Query Language",
        ans :1,
    },
    {   category:"backend",
        question:"Which HTTP method is used to retrieve data from a server in a RESTful API?",
        option1:"GET",
        option2:"POST",
        option3:"PUT",
        ans :1,
    },
    {   category:"backend",
        question:"What does the term \"middleware\" refer to in the context of web development?",
        option1:"Software that provides user interfaces",
        option2:"Code that connects a web application to a database",
        option3:"Code that acts as a bridge between different components",
        ans :3,
    },
    
    {   category:"backend",
        question:"What is the purpose of Node.js in backend development?",
        option1:"Database management",
        option2:"Server-side JavaScript execution",
        option3:"Frontend styling",
        ans :2,
    },
    {   category:"backend",
        question:"Which database type is known for its schema-less structure?",
        option1:"MySQL",
        option2:"MongoDB",
        option3:"PostgreSQL",
        ans :2,
    },
    {   category:"backend",
        question:"What is the purpose of the Express.js framework in Node.js?",
        option1:"Database management",
        option2:"Frontend development",
        option3:"Backend framework for Node.js",
        ans :3,
    },

]